### ISSUE TITLE
Add Groups

### ISSUE THREAD

**Issue by nprail** [HexagonMinecraft/mc-registry#15]
Add plugin groups. 

## To-Do
- [ ] Build Groups API
- [ ] Build Private Groups API
- [ ] Add Groups to Client Side

## API
- `GET /groups/:groupName`
- `GET /groups/:groupName/plugins`
- `GET /groups/:groupName/members`
- `GET /plugin/@:groupName/:pluginId`

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
